# global config
global: 
  scrape_interval:      10s
  evaluation_interval:  10s


scrape_configs:
  - job_name: 'cadvisor'

    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'haproxy'


    static_configs:
    - targets: ['haproxy-exporter:9101']






    